-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 15:10:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cardapion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cardapion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cardapion` DEFAULT CHARACTER SET utf8mb4 ;
USE `cardapion` ;

-- -----------------------------------------------------
-- Table `cardapion`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapion`.`restaurante` (
  `idrestaurante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `proprietario` VARCHAR(200) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idrestaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapion`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapion`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `restaurante_idrestaurante` INT NOT NULL,
  PRIMARY KEY (`idcategoria`),
  INDEX `fk_categoria_restaurante_idx` (`restaurante_idrestaurante` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_restaurante`
    FOREIGN KEY (`restaurante_idrestaurante`)
    REFERENCES `cardapion`.`restaurante` (`idrestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapion`.`prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapion`.`prato` (
  `idprato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `descricao` VARCHAR(300) NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idprato`),
  INDEX `fk_prato_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_prato_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `cardapion`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapion`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapion`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardapion`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardapion`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `estrelaCardapio` INT NULL,
  `estrelaRestaurante` INT NULL,
  `comentario` VARCHAR(400) NULL,
  `resposta` VARCHAR(400) NULL,
  `restaurante_idrestaurante` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_avaliacao_restaurante1_idx` (`restaurante_idrestaurante` ASC) VISIBLE,
  INDEX `fk_avaliacao_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_restaurante1`
    FOREIGN KEY (`restaurante_idrestaurante`)
    REFERENCES `cardapion`.`restaurante` (`idrestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `cardapion`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
